In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('loan_data.csv')
df.head()

   Age  Income  LoanAmount  CreditScore  Approved
0   22   71948       35000          561         1
1   21   12282        1000          504         0
2   25   12438        5500          635         1
3   23   79753       35000          675         1
4   24   66135       35000          586         1

In [5]:
print(df.shape)
df.info()
df.describe()

(45000, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          45000 non-null  int64
 1   Income       45000 non-null  int64
 2   LoanAmount   45000 non-null  int64
 3   CreditScore  45000 non-null  int64
 4   Approved     45000 non-null  int64
dtypes: int64(5)
memory usage: 1.7 MB

                Age        Income    LoanAmount   CreditScore      Approved
count  45000.000000  4.500000e+04  45000.000000  45000.000000  45000.000000
mean      27.764178  8.031905e+04   9583.157556    632.608756      0.222222
std        6.045108  8.042250e+04   6314.886691     50.435865      0.415744
min       20.000000  8.000000e+03    500.000000    390.000000      0.000000
25%       24.000000  4.720400e+04   5000.000000    601.000000      0.000000
50%       26.000000  6.704800e+04   8000.000000    640.000000      0.000000
75%       30.000000  9.578925e+04  12237.250000    670.000000      0.000000
max      144.000000  7.200766e+06  35000.000000    850.000000      1.000000

In [6]:
df.isna().sum()

Age            0
Income         0
LoanAmount     0
CreditScore    0
Approved       0
dtype: int64

In [7]:
df.nunique()

Age               60
Income         33989
LoanAmount      4483
CreditScore      340
Approved           2
dtype: int64

In [11]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 1

In [12]:
df = df.drop_duplicates()

In [13]:
df.shape

(44999, 5)

In [14]:
df["Approved"].value_counts()

Approved
0    34999
1    10000
Name: count, dtype: int64

In [15]:
x = df.drop("Approved", axis=1)
y = df["Approved"]

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(class_weight="balanced",random_state=42)

In [24]:
model.fit(x_train, y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [25]:
y_pred = model.predict(x_test)

In [26]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7844444444444445

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[6051  945]
 [ 995 1009]]

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86      6996
           1       0.52      0.50      0.51      2004

    accuracy                           0.78      9000
   macro avg       0.69      0.68      0.69      9000
weighted avg       0.78      0.78      0.78      9000

In [29]:
import joblib
joblib.dump(model, "decision_tree_model.pkl")

['decision_tree_model.pkl']